// import Timer = NodeJS.Timer;

export const SET_LANGUAGE_REQUESTED = 'SET_LANGUAGE';
export const RESET_STATE_REQUESTED = 'RESET_STATE';
export const WELCOME_SUBMITTED = 'WELCOME_SUBMITTED';
export const ACCOUNT_DETAILS_SUBMIT_STARTED = 'ACCOUNT_DETAILS_SUBMIT_STARTED';
export const ACCOUNT_DETAILS_SUBMIT_SUCCEEDED = 'ACCOUNT_DETAILS_SUBMIT_SUCCEEDED';
export const ACCOUNT_DETAILS_SUBMIT_FAILED = 'ACCOUNT_DETAILS_SUBMIT_FAILED';
export const IDENTIFICATION_SUBMIT_STARTED = 'IDENTIFICATION_SUBMIT_STARTED';
export const IDENTIFICATION_SUBMIT_SUCCEEDED = 'IDENTIFICATION_SUBMIT_SUCCEEDED';
export const IDENTIFICATION_SUBMIT_FAILED = 'IDENTIFICATION_SUBMIT_FAILED';
export const PASSWORD_SUBMIT_STARTED = 'PASSWORD_SUBMIT_STARTED';
export const PASSWORD_SUBMIT_SUCCEEDED = 'PASSWORD_SUBMIT_SUCCEEDED';
export const PASSWORD_SUBMIT_FAILED = 'PASSWORD_SUBMIT_FAILED';
export const CONFIRMATION_SUBMIT_STARTED = 'CONFIRMATION_SUBMIT_STARTED';
export const CONFIRMATION_SUBMIT__SUCCEEDED = 'CONFIRMATION_SUBMIT__SUCCEEDED';
export const CONFIRMATION_SUBMIT__FAILED = 'CONFIRMATION_SUBMIT__FAILED';
export const CURRENT_STEP_CHANGED = 'CURRENT_STEP_CHANGED';

export const TIMER_ADD_TIME_REQUESTED = 'TIMER_ADD_TIME';

/** NUMERIC CONSTANTS **/
export const TIMEOUT_VALUE = 600000;  // in milliseconds
export const TIMER_POPUP_VALUE = 60000; // in milliseconds

// export const TIMER: Timer = {
//   title: 'Your session will expire in',
//   message: 'Need more time?',
//   value: TIMEOUT_VALUE,
//   count: 1
// };
