export const environment = {
  production: true,
  french_agreement_link: 'https://www.bmo.com/accueil/popups/global/convention-de-services-electroniques',
  english_agreement_link: 'https://www.bmo.com/home/popups/global/firstbank-service-agreement',
  bmo_home_english: 'https://www.bmo.com/main/personal',
  bmo_home_french: 'https://www.bmo.com/principal/particuliers',
  english_subscription_centre_link: 'https://www.bmo.com/home/about/banking/privacy-security/subscription-centre',
  french_subscription_centre_link: 'https://www.bmo.com/accueil/a-propos-de-bmo/services-bancaires/confidentialite-securite/abonnement',
  english_online_banking_link: 'https://www1.bmo.com/',
  french_online_banking_link: 'https://www1.bmo.com/onlinebanking/cgi-bin/netbnx/NBmain?product=6',
  english_mobile_online_banking_link: 'https://m2.bmo.com/BMOMobile/apps/services/www/BMOMobileBanking/mobilewebapp/default/BMOMobileBanking.html',
  french_mobile_online_banking_link: 'https://m2.bmo.com/BMOMobile/apps/services/www/BMOMobileBanking/mobilewebapp/default/BMOMobileBanking.html',
  APPLE_ITUNES_EN_IPHONE_DOWNLOAD_LINK: 'https://itunes.apple.com/ca/app/bmo-mobile-banking/id429080319?mt=8',
  APPLE_ITUNES_FR_IPHONE_DOWNLOAD_LINK: 'https://itunes.apple.com/ca/app/services-mobiles-bmo/id429080319?l=fr&mt=8',
  APPLE_ITUNES_EN_IPAD_DOWNLOAD_LINK: 'https://itunes.apple.com/ca/app/bmo-banking-investorline/id917762613?mt=8',
  APPLE_ITUNES_FR_IPAD_DOWNLOAD_LINK: 'https://itunes.apple.com/ca/app/apple-store/id917762613?mt=8&l=fr',
  GOOGLE_PLAY_EN_DOWNLOAD_LINK: 'https://play.google.com/store/apps/details?id=com.bmo.mobile&hl=en',
  GOOGLE_PLAY_FR_DOWNLOAD_LINK: 'https://play.google.com/store/apps/details?id=com.bmo.mobile&hl=fr',
  signInLink: 'http://bmo.com',
  forgotPasswordLink: 'http://bmo.com/forgot',
  alreadyRegisteredContactLink: 'https://www.bmo.com/main/contact-us',
  alreadyRegisteredContactLinkFrench: 'https://www.bmo.com/principal/contactez-nous',
  signInLinkEn: 'https://www1.bmo.com/onlinebanking/cgi-bin/netbnx/NBmain?product=5',
  signInLinkFr: 'https://www1.bmo.com/onlinebanking/cgi-bin/netbnx/NBmain?product=6'
};
